entity_comparison.entity_comparison.*:
  type: config_entity
  label: 'Entity comparison config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    add_link_text:
      type: label
      label: 'Text for the link "add comparison"'
    remove_link_text:
      type: label
      label: 'Text for the link to "remove from the comparison"'
    limit:
      type: integer
      label: 'The limit on the number of compared items ("0" - no limit)'
    entity_type:
      type: string
      label: 'Entity type'
    bundle_type:
      type: string
      label: 'Bundle type'